language: python

cache: pip

python:
  - "3.6"

install:
  - cd src
  - sudo apt install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg libav-tools
  - pip install -r requirements.txt

script:
  -
  - coverage run -m unittest discover
  - codecov --token=b26cfa94-4123-44a2-a0ff-b60a6a410d83
